TOP=testbench
SEED=1

all: sim run

## Do NOT change the content below unless you know what you're doing
FLAGS =  -Wall --trace --sv --timing
FLAGS += -O3 --compiler gcc -CFLAGS -std=gnu++20
FLAGS += -x-initial unique
FLAGS += -x-assign unique
FLAGS += --assert
FLAGS += --build -j 0 --quiet
LFLAGS = --lint-only --sv --timing --quiet
RFLAGS =  +verilator+seed+$(SEED)
RFLAGS += +verilator+quiet
FLAGS += --Wno-UNUSEDSIGNAL

TARGET = -f ./flist

.PHONY: lint
lint:
	@echo "-> LINT"
	verilator $(LFLAGS) $(TARGET)

.PHONY: sim
# sim:
# 	@echo "-> SIMULATION"
# 	verilator $(FLAGS) $(TARGET)
sim:
	@echo "-> SIMULATION"
	verilator --cc $(FLAGS) $(TARGET) --exe testbench.cpp
	@make -C obj_dir -f V$(TOP).mk V$(TOP)

.PHONY: run
run:
	@echo "-> RUN"
	./obj_dir/V$(TOP) $(RFLAGS)

.PHONY: wave
wave:
	gtkwave wave.vcd wave.gtkw 2>/dev/null

.PHONY: clean
clean:
	@echo "-> CLEAN"
	@rm -rf ./obj_dir *.vcd



